# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='article_slug',
        ),
        migrations.AddField(
            model_name='articletags',
            name='fake_field',
            field=models.CharField(default='pankaj', max_length=10),
            preserve_default=False,
        ),
    ]
