# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 11:50
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='commentlikes',
            name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='commentreply',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-article_views', 'created'), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='ArticleTags',
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
