# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20170821_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlelikes',
            options={'verbose_name': 'Article like', 'verbose_name_plural': 'Article Likes'},
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comments', verbose_name='Related Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='articlelikes',
            unique_together=set([('article_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='commentreply',
            unique_together=set([('comment_id', 'user_id')]),
        ),
    ]
