# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180810_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_tags', to='blog.ArticleTags', verbose_name='tags'),
        ),
    ]
