# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 03:26
from __future__ import unicode_literals

import blog.blog
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170829_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=blog.blog.CompressedTextField(blank=True),
        ),
    ]
