# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-30 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170924_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.TextField(blank=True, help_text='keaywords for indexing your article in search engins'),
        ),
    ]
