# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_article_flike_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_description',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
