# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_article_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-article_views', 'created')},
        ),
        migrations.AlterUniqueTogether(
            name='articlelikes',
            unique_together=set([]),
        ),
    ]
