# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20171005_0739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlelikes',
            unique_together=set([('article_id', 'user_id')]),
        ),
    ]
