# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171015_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
