# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='static/blog/article_images'),
        ),
    ]
