# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default=b'/media/images/profile_images/default_user.png', upload_to='images/profile_images/')),
                ('birth_date', models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='Birth Date')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Moderator'), (3, 'Normal')], help_text='Admin(1)/Moderator(2)/Normal(3)')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('notspecified', "Don't Specify")], default='notspecified', max_length=15)),
                ('about_me', models.TextField(blank=True, max_length=1000)),
                ('short_intro', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('article_reads', models.ManyToManyField(blank=True, related_name='user_reads', to='blog.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
