# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default=9662766166, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'moderator'), (3, 'normal')], default=3, help_text='Admin(1)/Moderator(2)/Normal(3)'),
            preserve_default=False,
        ),
    ]
