# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default=b'/media/images/profile_images/default_user.png', upload_to='static/src/images/user_profile/cover/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=b'/media/images/profile_images/default_user.png', upload_to='images/profile_images/'),
        ),
    ]
