# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_article_author'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='article_reads',
            field=models.ManyToManyField(blank=True, related_name='user_reads', to='blog.Article'),
        ),
    ]
