# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20170804_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='static/src/images/user_profile/img/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Moderator'), (3, 'Normal')], help_text='Admin(1)/Moderator(2)/Normal(3)'),
        ),
    ]
