# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170821_1747'),
        ('user_profile', '0003_auto_20170820_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='article_readed',
            field=models.ManyToManyField(related_name='myArticles', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Dont Specify')], max_length=1),
        ),
    ]
