# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20170827_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='article_readed',
            field=models.ManyToManyField(blank=True, related_name='myArticles', to='blog.Article'),
        ),
    ]
