# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20170827_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='article_readed',
            field=models.ManyToManyField(to='blog.Article'),
        ),
    ]
