# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_article_state'),
        ('user_profile', '0009_auto_20170827_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='article_readed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='article_reads',
            field=models.ManyToManyField(related_name='user_reads', to='blog.Article'),
        ),
    ]
