# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20170828_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='article_reads',
            field=models.ManyToManyField(blank=True, related_name='user_reads', to='blog.Article'),
        ),
    ]
