# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_auto_20171011_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/src/images/user_profile/img/avatar.png', upload_to='static/src/images/user_profile/img/'),
        ),
    ]
