# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_userprofile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='Birth Date'),
        ),
    ]
