# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_auto_20171015_1549'),
    ]

    operations = [
    ]
