# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_self', '0002_myself_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myself',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
